image: scratch

before_script:
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.4
  - echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
  - echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
  - asdf plugin-add python
  - asdf global python 3.7.3

check-code:
  image: python:3.7-alpine
  type: build
  script:
    - pip install pipenv
    - pipenv run python manage.py check
    # - pipenv run pylint --load-plugins=pylint_django project
    # - pipenv run pylint --load-plugins=pylint_django app