version: '3.1'

services:
  db:
    image: docker.io/yobasystems/alpine-mariadb:10.4.15
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: glowup
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    external: true