# Generated by Django 2.1.3 on 2019-02-11 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Booking', verbose_name='Booking'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ServiceCategory', verbose_name='Service Category'),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee'),
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.CustomerLocation'),
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assigned by'),
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='employee',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registered by'),
        ),
        migrations.AddField(
            model_name='employee',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Customer'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Customer'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.CustomerLocation', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='abudance',
            field=models.ForeignKey(db_column='abudance', limit_choices_to={'is_active': True, 'type_category': 11}, on_delete=django.db.models.deletion.CASCADE, related_name='abudance', to='config.Type', verbose_name='Abudance'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Booking'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='chemical_service',
            field=models.ForeignKey(db_column='chemical_service', limit_choices_to={'is_active': True, 'type_category': 17}, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_service', to='config.Type', verbose_name='Previous Chemical Service'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='comfort_level',
            field=models.ForeignKey(db_column='comfort_level', limit_choices_to={'is_active': True, 'type_category': 10}, on_delete=django.db.models.deletion.CASCADE, related_name='comfort_level', to='config.Type', verbose_name='Styling comfort level'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='commitment',
            field=models.ForeignKey(db_column='commitment', limit_choices_to={'is_active': True, 'type_category': 6}, on_delete=django.db.models.deletion.CASCADE, related_name='commitment', to='config.Type', verbose_name='Commitment to Salon Visits'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='condition',
            field=models.ForeignKey(db_column='condition', limit_choices_to={'is_active': True, 'type_category': 14}, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='config.Type', verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='diameter',
            field=models.ForeignKey(db_column='diameter', limit_choices_to={'is_active': True, 'type_category': 12}, on_delete=django.db.models.deletion.CASCADE, related_name='diameter', to='config.Type', verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='distress',
            field=models.ForeignKey(db_column='distress', limit_choices_to={'is_active': True, 'type_category': 15}, on_delete=django.db.models.deletion.CASCADE, related_name='distress', to='config.Type', verbose_name='Type of Distress'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='hair_formation',
            field=models.ForeignKey(db_column='hair_formation', limit_choices_to={'is_active': True, 'type_category': 13}, on_delete=django.db.models.deletion.CASCADE, related_name='hair_formation', to='config.Type', verbose_name='Hair Formation'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='hair_goals',
            field=models.ForeignKey(db_column='hair_goals', limit_choices_to={'is_active': True, 'type_category': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='hair_goals', to='config.Type', verbose_name='Hair Goals'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='personal_style',
            field=models.ForeignKey(db_column='personal_style', limit_choices_to={'is_active': True, 'type_category': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='personal_style', to='config.Type', verbose_name='Personal Style'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='professional_style',
            field=models.ForeignKey(db_column='professional_style', limit_choices_to={'is_active': True, 'type_category': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='professional_style', to='config.Type', verbose_name='Professional Style'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='skin_tone',
            field=models.ForeignKey(db_column='skin_tone', limit_choices_to={'is_active': True, 'type_category': 16}, on_delete=django.db.models.deletion.CASCADE, related_name='skin_tone', to='config.Type', verbose_name='Skin Tone'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='styling_preferences',
            field=models.ForeignKey(db_column='styling_preferences', limit_choices_to={'is_active': True, 'type_category': 9}, on_delete=django.db.models.deletion.CASCADE, related_name='styling_preferences', to='config.Type', verbose_name='How you style your hair'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='time_spending',
            field=models.ForeignKey(db_column='time_spending', limit_choices_to={'is_active': True, 'type_category': 7}, on_delete=django.db.models.deletion.CASCADE, related_name='time_spending', to='config.Type', verbose_name='Styling time spent at home'),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='versality',
            field=models.ForeignKey(db_column='versality', limit_choices_to={'is_active': True, 'type_category': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='versality', to='config.Type', verbose_name='Versality'),
        ),
        migrations.AddField(
            model_name='client',
            name='create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registered by'),
        ),
        migrations.AddField(
            model_name='client',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Customer'),
        ),
        migrations.AddField(
            model_name='client',
            name='introduced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Client', verbose_name='Introduced by'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='create',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.CustomerLocation', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='booking',
            name='prefered_employee',
            field=models.ForeignKey(blank=True, db_column='prefered_employee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefered_employee', to='app.Employee', verbose_name='Prefered Employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule_employee',
            field=models.ForeignKey(blank=True, db_column='schedule_employee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_employee', to='app.Employee', verbose_name='Scheduled Employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.ForeignKey(blank=True, db_column='service_type', limit_choices_to={'is_active': True, 'type_category': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='config.Type', verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Type', verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('employee_code', 'customer')},
        ),
    ]
