# Generated by Django 2.1.3 on 2019-02-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_booking_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule_remark',
            field=models.TextField(max_length=250, verbose_name='Remark'),
        ),
    ]
