# Generated by Django 2.1.3 on 2019-02-16 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190216_0422'),
        ('app', '0004_auto_20190216_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsession',
            name='face_type',
            field=models.ForeignKey(db_column='face_type', default=1, limit_choices_to={'is_active': True, 'type_category': 18}, on_delete=django.db.models.deletion.CASCADE, related_name='face_type', to='config.Type', verbose_name='Face Type'),
        ),
    ]
