# Generated by Django 2.1.3 on 2019-02-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190216_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Attachments')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'app_session_image',
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='clientsession',
            options={'default_permissions': (), 'verbose_name_plural': 'Client Session'},
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'default_permissions': (), 'verbose_name_plural': 'Services of Bookings'},
        ),
        migrations.AddField(
            model_name='sessionimages',
            name='client_session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ClientSession'),
        ),
    ]
