# Generated by Django 2.1.3 on 2019-02-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190217_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionimages',
            old_name='client_session_id',
            new_name='client_session',
        ),
    ]
