# Generated by Django 2.1.3 on 2019-02-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customeruser_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='Time Zone'),
        ),
    ]
