# Generated by Django 2.1.3 on 2019-02-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190222_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'default_permissions': (), 'permissions': (('add_booking', 'Can Add Booking'), ('change_booking', 'Can Change Booking'), ('view_bookings', 'Can View Bookings'), ('add_future_booking', 'Can Add Future Booking'), ('view_future_bookings', 'Can View Future Bookings'), ('change_future_booking', 'Can Change Future Booking')), 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
