# Generated by Django 2.1.7 on 2019-03-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190222_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsession',
            name='abudance',
            field=models.ForeignKey(db_column='abudance', limit_choices_to={'is_active': True, 'type_category': 11}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abudance', to='config.Type', verbose_name='Abudance'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='chemical_service',
            field=models.ForeignKey(db_column='chemical_service', limit_choices_to={'is_active': True, 'type_category': 17}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_service', to='config.Type', verbose_name='Previous Chemical Service'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='comfort_level',
            field=models.ForeignKey(db_column='comfort_level', limit_choices_to={'is_active': True, 'type_category': 10}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comfort_level', to='config.Type', verbose_name='Styling comfort level'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='commitment',
            field=models.ForeignKey(db_column='commitment', limit_choices_to={'is_active': True, 'type_category': 6}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitment', to='config.Type', verbose_name='Commitment to Salon Visits'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='condition',
            field=models.ForeignKey(db_column='condition', limit_choices_to={'is_active': True, 'type_category': 14}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='config.Type', verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='diameter',
            field=models.ForeignKey(db_column='diameter', limit_choices_to={'is_active': True, 'type_category': 12}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diameter', to='config.Type', verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='distress',
            field=models.ForeignKey(db_column='distress', limit_choices_to={'is_active': True, 'type_category': 15}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distress', to='config.Type', verbose_name='Type of Distress'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='face_type',
            field=models.ForeignKey(db_column='face_type', limit_choices_to={'is_active': True, 'type_category': 18}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_type', to='config.Type', verbose_name='Face Type'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='hair_formation',
            field=models.ForeignKey(db_column='hair_formation', limit_choices_to={'is_active': True, 'type_category': 13}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hair_formation', to='config.Type', verbose_name='Hair Formation'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='hair_goals',
            field=models.ForeignKey(db_column='hair_goals', limit_choices_to={'is_active': True, 'type_category': 5}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hair_goals', to='config.Type', verbose_name='Hair Goals'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='personal_interests',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personal Interests'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='personal_style',
            field=models.ForeignKey(db_column='personal_style', limit_choices_to={'is_active': True, 'type_category': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_style', to='config.Type', verbose_name='Personal Style'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='preferences',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What do you like/dislike about your hair?'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='products',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What products are you currently using?'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='professional_style',
            field=models.ForeignKey(db_column='professional_style', limit_choices_to={'is_active': True, 'type_category': 4}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_style', to='config.Type', verbose_name='Professional Style'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='skin_tone',
            field=models.ForeignKey(db_column='skin_tone', limit_choices_to={'is_active': True, 'type_category': 16}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skin_tone', to='config.Type', verbose_name='Skin Tone'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='styling_preferences',
            field=models.ForeignKey(db_column='styling_preferences', limit_choices_to={'is_active': True, 'type_category': 9}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styling_preferences', to='config.Type', verbose_name='How you style your hair'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='time_spending',
            field=models.ForeignKey(db_column='time_spending', limit_choices_to={'is_active': True, 'type_category': 7}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_spending', to='config.Type', verbose_name='Styling time spent at home'),
        ),
        migrations.AlterField(
            model_name='clientsession',
            name='versality',
            field=models.ForeignKey(db_column='versality', limit_choices_to={'is_active': True, 'type_category': 8}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versality', to='config.Type', verbose_name='Versality'),
        ),
    ]
