# Generated by Django 2.2.1 on 2019-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190413_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Session Ended on'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule_remark',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Session Started on'),
        ),
    ]
