# Generated by Django 2.1.3 on 2019-02-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_category',
            field=models.IntegerField(choices=[(1, 'Status'), (2, 'Booking Type'), (3, 'Personal Style'), (4, 'Professional Style'), (5, 'Hair Goals'), (6, 'Commitment to Salon Visits'), (7, 'Styling Time'), (8, 'Versality'), (9, 'How you Style'), (10, 'Styling Comfort Level'), (11, 'Abudance'), (12, 'Diameter'), (13, 'Hair Formation'), (14, 'Condition'), (15, 'Type of Distress'), (16, 'Skin Tone'), (17, 'Previous Chemical Service'), (18, 'Face Type')], verbose_name='Type Categorization'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_description',
            field=models.CharField(max_length=50, verbose_name='Type Description'),
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('type_description', 'type_category')},
        ),
    ]
